### ISSUE TITLE
Montar un try demostration

### ISSUE THREAD

**Issue by oskarcalvo** [oskarcalvo/googlelogin#5]
https://www.drupal.org/project/filelist_formatter
Resources           Read license Try out a de
demonstration View project translations

**Comment by keopx** [comment]
![Try demostration example](https://cloud.githubusercontent.com/assets/537583/20244674/5e4f76be-a98b-11e6-822d-d93c2d405b6f.png)

**Comment by oskarcalvo** [comment]
Ya se ha creado la página de demo que lanza simpletest.me con el módulo preseleccionado.
